{
 "title": "LinkTap Water Timer",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Gateway Firmware Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "linktap_gateway_version" }
   ]
  },
  {
   "title": "Received Messager Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(linktap_gateway_msg_counter[1h])*3600",
     "legendFormat": "Gateway"
    },
    {
     "expr": "rate(linktap_watertimer_msg_counter[1h])*3600",
     "legendFormat": "Device: {{dev_type}} - {{dev_name}}"
    }
   ]
  },
  {
   "title": "Water flow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    { "expr": "linktap_watertimer_speed", "legendFormat": "{{dev_type}} - {{dev_name}}" }
   ]
  },
  {
   "title": "Battery Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "linktap_watertimer_battery", "legendFormat": "{{dev_type}} - {{dev_name}}" }
   ]
  },
  {
   "title": "Water volume",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    { "expr": "linktap_watertimer_volume", "legendFormat": "{{dev_type}} - {{dev_name}}" }
   ]
  },
  {
   "title": "Signal Strength",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "linktap_watertimer_signal", "legendFormat": "{{dev_type}} - {{dev_name}}" }
   ]
  }
 ]
}